// Replies generated by a terminal emulator, not keyboard input. The server's headless emulator
// answers the real output once. The browser must not answer it again, especially during replay.
/** Focus in/out reports requested by the running program; not keyboard input. */
export function isFocusReport(data: string): boolean {
  return /^(?:\x1b\[[IO])+$/.test(data);
}

export function isTerminalReport(data: string): boolean {
  return /^(?:\x1b\[[?>=]?[\d;:]*[cnRt]|\x1b\](?:4|10|11|12);[^\x07\x1b]*(?:\x07|\x1b\\)|\x1bP[^\x1b]*\x1b\\)+$/.test(data);
}
